python main.py --cf configs/path_mnist.yaml
python main.py --cf configs/derma_mnist.yaml
python main.py --cf configs/oct_mnist.yaml
python main.py --cf configs/pneumonia_mnist.yaml
python main.py --cf configs/breast_mnist.yaml
python main.py --cf configs/blood_mnist.yaml
python main.py --cf configs/tissue_mnist.yaml
python main.py --cf configs/organ_a_mnist.yaml
python main.py --cf configs/organ_c_mnist.yaml
python main.py --cf configs/organ_s_mnist.yaml